### ISSUE TITLE
Bibtex parser

### ISSUE THREAD

**Issue by James-Yu** [tamuratak/latex-utensils#1]
It would be great if bibtex can be also parsed into AST. Some good candidates are

https://github.com/dsifford/astrocite/blob/master/packages/astrocite-bibtex/src/grammar.pegjs
https://gist.github.com/larsgw/1d76e1d06ae747e69b9af21f2af079ed

But they both have flaws. The first one cannot parse entry names with understore, e.g., `__markedentry` produced by jabref. The second one cannot work with entries with `month = jan`.

**Comment by tamuratak** [comment]
I have implemented a BibTeX parser as `bibtexParser`. Notice that I have bumped the version of `latex-utensils` to v1.0.0. You have to edit  the `dependencies` of `package.json`.

```typescript
import {bibexParser} from 'latex-utensils';
const bib = `
@article{sample1,
    title={sample title}
}
@article{sample2, title={sample title2} }
`
const ast = bibtexParser.parse(bib)
```
