### ISSUE TITLE
verbatim* env is not supported

### ISSUE THREAD

**Issue by pddg** [tamuratak/latex-utensils#12]
## Environment

- macOS Catalina 10.15.2
- Node v12.14.0
- latex-utensils v1.2.2

## Sample tex source

Save this as `sample.tex`

```tex
\begin{verbatim*}
  abc
\end{verbatim*}
```

## Parse

```bash
$ npx luparse sample.tex
```

## Expected

`\begin{verbatim*} ~ \end{verbatim*}` is a type of verbatim environment. It visualizes the white spaces. 
So I expect the following AST.

```json
{
  "kind": "ast.root",
  "content": [
    {
      "kind": "env.verbatim",
      "name": "verbatim",
      "content": "\n  abc\n"
    },
    {
      "kind": "env.verbatim",
      "name": "verbatim*",
      "content": "\n  abc\n"
    }
  ]
}
```

## Actual

latex-utensils does not recognize `verbatim*` as a verbatim environment but general environment. Its contents become an array of `text.string` node.

```json
{
  "kind": "ast.root",
  "content": [
    {
      "kind": "env.verbatim",
      "name": "verbatim",
      "content": "\n  abc\n"
    },
    {
      "kind": "env",
      "name": "verbatim*",
      "args": [],
      "content": [
        {
          "kind": "text.string",
          "content": "abc"
        }
      ]
    }
  ]
}
```

Therefore, if the latex command characters are used in `verbatim*` environment, latex-utensils raises a SyntaxError. For example, the following sample fails to parse.

```tex
\begin{verbatim}
  $ echo Hello
\end{verbatim}
\begin{verbatim*}
  $ echo Hello
\end{verbatim*}
```

```bash
$ npx luparse sample.tex
SyntaxError at line: 6, column: 16.
Expected "#", "$", "&", "[", "\0", "\\", "^", "_", "{", "~", any character, or special command but end of input found.
```

This error occurs in #11 as well.

**Comment by tamuratak** [comment]
Thank you for your reporting.

Closed by 8e277f4889cf7129c18cbb7e86fd943638b5dbbd.
