### ISSUE TITLE
Performance issue matching \left and \right

### ISSUE THREAD

**Issue by jugglingcats** [tamuratak/latex-utensils#17]
We have some medium size tex files that contain math equations, such as:

```
\begin{align*}
  N &= \sum \pqty{\rho V_i g}  \\
  &= \rho g \sum V_i && \left|\sum V_i = V\right.  \\
  &= \rho V g
\end{align*}
```

It seems that latex utensils parser has an issue with the `\right` when the character following doesn't match the character after `\left`. It takes a very long time to parse this file (particularly when it contains multiple such equations).

```
$ time node test
read file
done

real    0m9.357s
user    0m0.000s
sys     0m0.000s
```

If we replace `\right` in the file with `\right|`, we get:

```
$ time node test
read file
done

real    0m0.208s
user    0m0.015s
sys     0m0.000s
```

But now the formatting is not correct.

The tex file is 20kb in size and contains 10 equations containing `\left`.

**Comment by tamuratak** [comment]
Thank you for your reporting. If you still encounter this problem, please let me know.

**Comment by jugglingcats** [comment]
Thank you!
