### ISSUE TITLE
Extremely high parsing time

### ISSUE THREAD

**Issue by James-Yu** [tamuratak/latex-utensils#5]
It is quite common that `tex\latex\l3kernel\expl3-code.tex` is included in `.fls` file generated by LaTeX projects, even no LaTeX3 is used. However, the parser requires extremely long time to parse this file, which does not comply with latex grammar defined and produces an error. This is causing LaTeX-Workshop to hang after first-time building such projects. Is there a way to limit the maximum parsing time of a tex file?

**Comment by tamuratak** [comment]
Now, we can call the parser with a timeout option (in milliseconds):

```typescript
latexParser.parse(s, { timeout: 1000 } )
```
