### ISSUE TITLE
[Feature Request] Parse \def command

### ISSUE THREAD

**Issue by jlelong** [tamuratak/latex-utensils#8]
This is related to https://github.com/James-Yu/LaTeX-Workshop/issues/1707#issuecomment-568134887.

Consider the definition `\def\mbold#1{{\mathbb #1}}`, then `luparse` yields
```
    { kind: 'command', name: 'def', args: [] },
    { kind: 'command', name: 'mbold', args: [] },
    { kind: 'commandParameter', nargs: '1' },
    {
      kind: 'arg.group',
      content: [
        {
          kind: 'arg.group',
          content: [
            { kind: 'command', name: 'mathbb', args: [] },
            { kind: 'commandParameter', nargs: '1' }
          ]
        }
      ]
    }
```

It would be nice if the result were a single node, so that we could appy `stringify` to recover the command definition. I could make a hack in LW to achieve this, but I think it makes more sense to implement the feature directly in LU.

**Comment by tamuratak** [comment]
Closed by 588d5dcf535a50b6112758b1367b14607537221b.
